#!/usr/bin/python
from argparse import ArgumentParser
import json

parser = ArgumentParser(
    prog='ltxhelper',
    description='Manages LaTeX presets and creation of new projects.',
    epilog='Bottom text')

parser.add_argument('-p', dest="preset", help='which preset to use')
parser.add_argument('PROJECT', help='location and name of the project')
args = parser.parse_args()

print(args)